export const DATA_RESET = 'DATA_RESET' // 数据重置
export const STATE_TRANSITION = 'STATE_TRANSITION' // 状态流转变迁
export const REQ_LOADING = 'REQ_LOADING' // 请求加载
export const BEIN_STATER = 'BEIN_STATER' // 进行的状态
export const WAIT_TIME = 'WAIT_TIME' // 等待时间
export const CURR_WORDS_INDEX = 'CURR_WORDS_INDEX' // 当前高亮单词索引
export const IS_START_SONGS = 'IS_START_SONGS' // 是否开启儿歌
export const PROGRESS = 'PROGRESS' // 设置进度
export const CURR_AUDIO_SRC = 'CURR_AUDIO_SRC' // 当前音频地址
export const NURSERY_RHYME = 'NURSERY_RHYME' // 儿歌信息
export const IS_SHOW_SENTENCE_CN = 'IS_SHOW_SENTENCE_CN' // 是否显示句子的汉译
export const PLAY_STATE = 'PLAY_STATE' // 是否播放音频
export const IS_FINISH_PIC = 'IS_FINISH_PIC' // 当前pic是否完成
export const VIEW_WORD_DIC = 'VIEW_WORD_DIC' // 看单词词典释义
export const CURR_PIC_IDX = 'CURR_PIC_IDX'
