export const DATA_RESET = 'DATA_RESET' // 数据重置
export const STATE_TRANSITION = 'STATE_TRANSITION' // 状态流转变迁
export const REQ_LOADING = 'REQ_LOADING' // 请求加载
export const PICBOOK = 'PICBOOK' // 绘本列表子项的内容
// export const PIC_CONTENTS = 'PIC_CONTENTS' // 绘本内容
export const PROGRESS = 'PROGRESS' // 进度
export const CURR_PIC_IDX = 'CURR_PIC_IDX' // 当前pic索引
export const IS_FINISH_PIC = 'IS_FINISH_PIC' // 当前pic是否完成
export const IS_COVER_PIC = 'IS_COVER_PIC' // 是否封面
export const VIEW_WORD_DIC = 'VIEW_WORD_DIC' // 看单词词典释义
export const IS_SHOW_SENTENCE_CN = 'IS_SHOW_SENTENCE_CN' // 是否显示句子的汉译
export const PLAY_STATE = 'PLAY_STATE' // 是否播放音频
